### ISSUE TITLE
NotImplementedError: method pow is not implemented

### ISSUE THREAD

**Issue by giaovarus** [inisis/brocolli#61]
Traceback (most recent call last):
  File "/media/3255035b-77ce-41e8-8665-808657363219/deep-learning/predict_floder.py", line 147, in <module>
    main()
  File "/media/3255035b-77ce-41e8-8665-808657363219/deep-learning/predict_floder.py", line 104, in main
    pytorch_parser.convert()
  File "/home/miniconda3/envs/py39/lib/python3.9/site-packages/brocolli/converter/pytorch_caffe_parser.py", line 51, in convert
    self.text_net, self.binary_weights = self.gen_ir()
  File "/home/miniconda3/envs/py39/lib/python3.9/site-packages/brocolli/converter/pytorch_caffe_parser.py", line 396, in gen_ir
    raise NotImplementedError(
NotImplementedError: method pow is not implemented

**Comment by inisis** [comment]
Hi, power is added, thanks!
