### ISSUE TITLE
 Attempted to trace Detect, but tracing of legacy functions is not supported

### ISSUE THREAD

**Issue by Jianglongyu** [inisis/brocolli#7]
----------------------------------------------------------------
Traceback (most recent call last):
  File "pytorch_model_converter.py", line 51, in <module>
    pytorch_parser = PytorchParser(model_file, [3, 300, 300])
  File "/brocolli/tests/../converter/pytorch/pytorch_parser.py", line 104, in __init__
    self.pytorch_graph.build(self.input_shape)
  File "/brocolli/tests/../converter/pytorch/pytorch_graph.py", line 115, in build
    trace, output = torch.jit.get_trace_graph(self.model, (dummy_input, ))
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/brocolli/tests/../converter/pytorch/pytorch_graph.py", line 100, in set_training
    yield
  File "/brocolli/tests/../converter/pytorch/pytorch_graph.py", line 115, in build
    trace, output = torch.jit.get_trace_graph(self.model, (dummy_input, ))
  File "/usr/local/lib/python3.5/dist-packages/torch/jit/__init__.py", line 255, in get_trace_graph
    return LegacyTracedModule(f, nderivs=nderivs)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/jit/__init__.py", line 288, in forward
    out = self.inner(*trace_inputs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 479, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/brocolli/tests/ssd.py", line 163, in forward
    self.priors.type(x.data.type())                  # default boxes
RuntimeError: Attempted to trace Detect, but tracing of legacy functions is not supported
----------------------------------------------------------------

**Comment by inisis** [comment]
Hi, 
to make it work, you need to uncomment ssd.py line 156 which is return loc, conf. we need to transform  the feature extractor.
Best

**Comment by inisis** [comment]
此 issue 暂时关闭，有任何更新欢迎再次打开。
